trigger:
- main  # Change this to the branch you want to trigger the build on

pool:
  name: 'default'


steps:
# Step 1: Set Environment Variables
- script: |
    echo "Setting environment variables..."
    export MEND_EMAIL=$(MEND_EMAIL)
    export MEND_USER_KEY=$(MEND_USER_KEY)
    export MEND_URL=$(MEND_URL)
  displayName: 'Set Environment Variables'

# Step 2: Build C# project using NuGet
- script: |
    echo "Restoring NuGet packages and building C# project..."
    dotnet restore --artifacts-path ./.nuget
  displayName: 'Build C# Project'

# Step 3: Build Java project using Maven
- script: |
    echo "Building Java project using Maven..."
    mvn clean install
  displayName: 'Build Java Project'

# Step 4: Build Node.js project using npm
- script: |
    echo "Installing Node.js dependencies..."
    npm install
  displayName: 'Build Node.js Project'

# Step 5: Build Python project using pip
- script: |
    echo "Installing Python dependencies from requirements.txt..."
    pip install -r requirements.txt
  displayName: 'Build Python Project'

# Step 6: Placeholder for other commands
- script: |
    mend auth info
    mend sca -u -s "test//4goats"
  env: 
    MEND_USER_KEY: $(MEND_USER_KEY)
    MEND_EMAIL: $(MEND_EMAIL)
    MEND_URL: "https://saas-eu.whitesourcesoftware.com"
    MEND_ORGANIZATION: $(ORG_KEY)
    MEND_LOG_LEVEL: DEBUG
  displayName: 'Custom Commands'

# Step 7: Publish Mend SCA Logs as Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/agent/.mend/logs/sca/'
    ArtifactName: 'MendSCA_Logs'
    publishLocation: 'Container'
  displayName: 'Upload Mend SCA Logs as Artifact'