trigger:
- main  # Change this to the branch you want to trigger the build on

pool:
  name: 'default'

variables:
  - group: New variable group 02-Dec  # If using a variable group
  - name: MEND_EMAIL
    value: $(myKeyVaultSecret.MEND_EMAIL)  # Reference Key Vault secret
  - name: MEND_USER_KEY
    value: $(myKeyVaultSecret.MEND_EMAIL)  # Reference Key Vault secret
  - name: MEND_URL
    value: "https://saas-eu.whitesourcesoftware.com" 


steps:
# Step 1: Set Environment Variables
- script: |
    echo "Setting environment variables..."
    export MEND_EMAIL=$(MEND_EMAIL)
    export MEND_USER_KEY=$(MEND_USER_KEY)
    export MEND_URL=$(MEND_URL)
  displayName: 'Set Environment Variables'

# Step 2: Build C# project using NuGet
- script: |
    echo "Restoring NuGet packages and building C# project..."
    nuget restore
  displayName: 'Build C# Project'

# Step 3: Build Java project using Maven
- script: |
    echo "Building Java project using Maven..."
    mvn clean install
  displayName: 'Build Java Project'

# Step 4: Build Node.js project using npm
- script: |
    echo "Installing Node.js dependencies..."
    npm install
  displayName: 'Build Node.js Project'

# Step 5: Build Python project using pip
- script: |
    echo "Installing Python dependencies from requirements.txt..."
    pip install -r requirements.txt
  displayName: 'Build Python Project'

# Step 6: Placeholder for other commands
- script: |
    curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
    mend auth info
    mend sca -u -s "Tara City//test//4goats"
  displayName: 'Custom Commands'