trigger:
- main  # Change this to the branch you want to trigger the build on

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: New variable group 02-Dec  # If using a variable group
  - name: MEND_EMAIL
    value: $(myKeyVaultSecret.MEND_EMAIL)  # Reference Key Vault secret
  - name: MEND_USER_KEY
    value: $(myKeyVaultSecret.MEND_EMAIL)  # Reference Key Vault secret
  - name: MEND_URL
    value: "https://saas-eu.whitesourcesoftware.com" 


jobs:
- job: Build_CSharp
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - script: |
        echo "Building C# project using NuGet..."
        dotnet build MyCSharpProject.sln
      displayName: 'Build C# Project'

- job: Build_Java
  dependsOn: Build_CSharp  # This ensures Build_Java runs after Build_CSharp
  steps:
    - script: |
        echo "Building Java project using Maven..."
        mvn clean install
      displayName: 'Build Java Project'

- job: Build_Node
  dependsOn: Build_Java  # This ensures Build_Node runs after Build_Java
  steps:
    - script: |
        echo "Installing Node.js dependencies..."
        npm install
      displayName: 'Install Node.js Dependencies'

- job: Build_Python
  dependsOn: Build_Node  # This ensures Build_Python runs after Build_Node
  steps:
    - script: |
        echo "Installing Python dependencies..."
        pip install -r requirements.txt
      displayName: 'Install Python Dependencies'

- job: Placeholder
  dependsOn: Build_Python  # This ensures Placeholder runs after Build_Python
  steps:
    - script: |
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        mend auth info
        mend sca -u -s "Tara City//test//4goats"
      displayName: 'Custom Commands'